version: '3.8'

# 定义所有命名卷
volumes:
  chroma-data:          # ChromaDB向量数据库存储

services:
  fe-app:
    image: fe-container:first
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - audio-processor
      - mysql-container
      - redis-container
      - vector-database      
    # ports:
    #   - 3005:3000
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /home/ji/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: anki
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /home/ji/redis-data:/data
    networks:
      - common-network
  audio-processor:
    image: split-audio-audio-processor:first
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - common-network
  vector-database:
    image: chromadb/chroma
    ports:
      - 8000:8000
    volumes:
      - chroma-data:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
